# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8cy3hrgIUyRClnii7nv-irr_ve2IKZS
"""

name = input('Введите имя ')
print('Добро пожаловать '+ name)
